import {
  IconHome,
  IconUser,
  IconSettings,
  IconChevronRight,
  IconMenu2,
  IconX,
  IconChevronDown,
  IconWifi,
  IconCpu,
  IconRocket,
  IconSatellite,
  IconPlanet,
  IconPhotoPlus,
  IconBuildingCommunity,
  IconBolt,
  IconDeviceDesktopSearch,
  IconPhoto,
  IconRadar,
  IconWorld,
  IconBook,
  IconCamera,
  IconMessageCircle,
  IconBriefcase,
  IconArrowUpRight,
  IconArrowRight,
} from "@tabler/icons-react";

export const iconMap = {
  home: IconHome,
  user: IconUser,
  settings: IconSettings,
  "chevron-down": IconChevronDown,
  "chevron-right": IconChevronRight,
  menu: IconMenu2,
  close: IconX,
  rocket: IconRocket,
  satellite: IconSatellite,
  wifi: IconWifi,
  cpu: IconCpu,
  planet: IconPlanet,
  "image-plus": IconPhotoPlus,
  building: IconBuildingCommunity,
  lightning: IconBolt,
  "desktop-search": IconDeviceDesktopSearch,
  image: IconPhoto,
  radar: IconRadar,
  globe: IconWorld,
  book: IconBook,
  camera: IconCamera,
  message: IconMessageCircle,
  briefcase: IconBriefcase,
  "arrow-right": IconArrowRight,
  "arrow-up-right": IconArrowUpRight,
} as const;

export type IconName = keyof typeof iconMap;
